spring:
  profiles:
    active:

  thymeleaf:
    cache: false

  springdoc:
    packages-to-scan: cart
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
      path: cart.html
      tags-sorter: alpha
      operations-sorter: alpha
    api-docs:
      path: /cart-api-docs
      groups:
        enabled: true
    cache:
      disabled: true
