  spring.thymeleaf.cache: false
  spring:
    config:
      import: secret.properties, application-datasource.yml
      sql:
        init:
          mode: always

  server:
    port: 443
    ssl:
      enabled: true
      enabled-protocols:
        - TLSv1.1
        - TLSv1.2
      key-store: "classpath:${KEYSTORE}"
      key-store-password: ${PASSWORD}
      key-store-type: "PKCS12"
