#version: '3'
#
#services:
#  mysql:
#    container_name: shopping_db
#    image: mysql/mysql-server:5.7
#    environment:
#      MYSQL_DATABASE: shopping_cart
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_ROOT_PASSWORD: 1234
#      TZ: 'Asia/Seoul'
#    ports:
#      - 13306:3306
#    command:
#      - "mysqld"
#      - "--character-set-server=utf8mb4"
#      - "--collation-server=utf8mb4_unicode_ci"
