name: Deploy to EC2

on:
  push:
    branches:
      - deploy

  deploy:
    runs-on: self-hosted
    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/jwp-shopping-order

      - uses: actions/checkout@v3
      - name: copy file
        run: |
          cp ./script/deploy.sh .
      - name: deploy
        run: |
          chmod +x ./deploy.sh
          sudo ./deploy.sh


